# Generated by Django 5.0.6 on 2024-08-18 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0003_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="frate",
                to="product_app.product",
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
