# Generated by Django 5.0.6 on 2024-08-22 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0002_remove_cart_seller_cart_item_seller"),
        ("order_app", "0002_remove_order_seller_order_item_seller"),
        ("product_app", "0004_alter_rate_product_alter_rate_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Code should not be more than 10 characters",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="initiated_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cart_app.cart",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                auto_now_add=True,
                help_text="The time when the order was first set",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="order_app.discount",
            ),
        ),
        migrations.AlterField(
            model_name="order_item",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="This item is related to which order",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="order_app.order",
            ),
        ),
        migrations.AlterField(
            model_name="order_item",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="This product",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product_app.product",
            ),
        ),
    ]
