# Generated by Django 5.1 on 2024-08-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='costumer name should be less than 50 characters', max_length=50, null=True, verbose_name='costumer_name')),
                ('city', models.CharField(blank=True, help_text='cities name should be less than 30 characters', max_length=30, null=True, verbose_name='city_name')),
                ('username', models.CharField(blank=True, help_text='username should be less than 36 characters', max_length=36, null=True)),
                ('password', models.CharField(blank=True, help_text='password should be less than 50 characters', max_length=36, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='seller name should be less than 50 characters', max_length=50, null=True, verbose_name='seller_name')),
                ('city', models.CharField(blank=True, help_text='cities name should be less than 30 characters', max_length=30, null=True, verbose_name='city_name')),
                ('username', models.CharField(blank=True, help_text='username should be less than 36 characters', max_length=36, null=True)),
                ('password', models.CharField(blank=True, help_text='password should be less than 50 characters', max_length=36, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
